
---
- hosts: webserver
  remote_user: ansible
  become: yes
  become_method: sudo

  vars_files:
  - ./loadbalancer_vars.yml

  roles:
  - role: apache-centos
    when: ansible_facts['os_family'] == "RedHat" 
  - role: apache-debian
    when: ansible_facts['os_family'] == "Debian"
