---
# tasks for apache-debian role
- name: Install Apache Server
  apt:
    name: apache2
    state: latest
    update_cache: yes 

- name: Start and enable services
  service:
    name: apache2
    state: started
    enabled: yes        
 
- name: Configure firewall
  ufw: 
    rule: allow
    port: "{{ item }}"
    state: enabled
  loop:
    - http
    - https
