---
# tasks for apache-debian role
- name: Install Apache Server
  apt:
    name: apache2
    state: latest
    update_cache: yes 

- name: Start and enable services
  service:
    name: apache2
    state: started
    enabled: yes        
 
- name: Configure firewall
  ufw: 
    rule: allow
    port: "{{ item }}"
    state: enabled
  loop:
    - http
    - https
 
- name: Create Loadbalancer configuration for Debian distributions
  template:
    src: templates/loadbalancer.j2
    dest: /etc/apache2/sites-enabled/000-default.conf
    owner: root
    mode: '0644'
  when: ansible_facts['os_family'] == "Debian"
  notify: Restart apache
